# must change root password when start a mysqld service
- name: pip install PyMySQL
  become: True
  pip: name=PyMySQL
- name: alter root password
  mysql_user:
    login_user: root
    login_password: ''
    login_host: localhost
    host_all: yes
    user: root
    password: "{{ mysql_root_password }}"
